// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjdr4ynk2YePy-jvzuXkecFE8_S87wDI',
    appId: '1:236638970291:web:771ad35a5c44dbb58eabc6',
    messagingSenderId: '236638970291',
    projectId: 'app1-4400',
    authDomain: 'app1-4400.firebaseapp.com',
    databaseURL: 'https://app1-4400-default-rtdb.firebaseio.com',
    storageBucket: 'app1-4400.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbDorZD_KwqX4fQMU9JfVa-vqa8IJIyws',
    appId: '1:236638970291:android:42c61bfed33496968eabc6',
    messagingSenderId: '236638970291',
    projectId: 'app1-4400',
    databaseURL: 'https://app1-4400-default-rtdb.firebaseio.com',
    storageBucket: 'app1-4400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrY85aQZMArJHo34s2RuyNSlRl0jchoNs',
    appId: '1:236638970291:ios:ebfa6e31bb411c0e8eabc6',
    messagingSenderId: '236638970291',
    projectId: 'app1-4400',
    databaseURL: 'https://app1-4400-default-rtdb.firebaseio.com',
    storageBucket: 'app1-4400.appspot.com',
    androidClientId: '236638970291-7bpb0674mj3sh2ljnphlkqcjt0n0671p.apps.googleusercontent.com',
    iosClientId: '236638970291-aea4j5juptkfit4t64eg5t09mbf01gmk.apps.googleusercontent.com',
    iosBundleId: 'com.testing.app1',
  );
}
